# Generated by Django 3.2.8 on 2021-12-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('labor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.employeeroles', to_field='labor_code')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.owner', to_field='business_name')),
            ],
        ),
    ]
