# Generated by Django 3.2.8 on 2021-12-03 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('vacation_start_date', models.DateField(blank=True, null=True)),
                ('vacation_end_date', models.DateField(blank=True, null=True)),
                ('labor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.employeeroles', to_field='labor_code')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owners', to_field='business_name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
