# Generated by Django 3.2.8 on 2021-12-10 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesworkschedule',
            name='labor_code',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='owners.employeeroles', to_field='labor_code'),
            preserve_default=False,
        ),
    ]
